In [2]:
import xarray as xr
import numpy as np

temperature has index 130

More info here: https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation

In [3]:
directory = "/pool/data/ERA5/E5/pl/an/1M/130/"
target = "/work/ka1176/paul/ML_tropospheric_temperatures/data/era5/"

In [4]:
!ls /pool/data/ERA5/E5/pl/an/1M/130/*194*

/pool/data/ERA5/E5/pl/an/1M/130/E5pl00_1M_1940_130.grb
/pool/data/ERA5/E5/pl/an/1M/130/E5pl00_1M_1940_130.index
/pool/data/ERA5/E5/pl/an/1M/130/E5pl00_1M_1941_130.grb
/pool/data/ERA5/E5/pl/an/1M/130/E5pl00_1M_1941_130.index
/pool/data/ERA5/E5/pl/an/1M/130/E5pl00_1M_1942_130.grb
/pool/data/ERA5/E5/pl/an/1M/130/E5pl00_1M_1942_130.index
/pool/data/ERA5/E5/pl/an/1M/130/E5pl00_1M_1943_130.grb
/pool/data/ERA5/E5/pl/an/1M/130/E5pl00_1M_1943_130.index
/pool/data/ERA5/E5/pl/an/1M/130/E5pl00_1M_1944_130.grb
/pool/data/ERA5/E5/pl/an/1M/130/E5pl00_1M_1944_130.index
/pool/data/ERA5/E5/pl/an/1M/130/E5pl00_1M_1945_130.grb
/pool/data/ERA5/E5/pl/an/1M/130/E5pl00_1M_1945_130.index
/pool/data/ERA5/E5/pl/an/1M/130/E5pl00_1M_1946_130.grb
/pool/data/ERA5/E5/pl/an/1M/130/E5pl00_1M_1946_130.index
/pool/data/ERA5/E5/pl/an/1M/130/E5pl00_1M_1947_130.grb
/pool/data/ERA5/E5/pl/an/1M/130/E5pl00_1M_1947_130.index
/pool/data/ERA5/E5/pl/an/1M/130/E5pl00_1M_1948_130.grb
/pool/data/ERA5/E5/pl/an/1M/130/E5pl00_1M_1948_130.index
/pool/data/ERA5/E5/pl/an/1M/130/E5pl00_1M_1949_130.grb
/pool/data/ERA5/E5/pl/an/1M/130/E5pl00_1M_1949_130.index

In [5]:
years =np.arange(1940,2023)

In [6]:
%%time
for year in years :
    print(year)
    ds = xr.open_dataset(directory + f"E5pl00_1M_{year}_130.grb", engine="cfgrib", indexpath='')
    ds = ds.sel(isobaricInhPa=[400,300,250,200,150])
    ds.to_netcdf(target + f"E5pl00_1M_{year}_130_ut.nc")

1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
CPU times: user 1min 6s, sys: 47.7 s, total: 1min 54s
Wall time: 2min 35s

In [ ]:
%%time
for year in years :
    print(year)
    ds = xr.open_dataset(directory + f"E5pl00_1M_{year}_130.grb", engine="cfgrib", indexpath='')
    ds = ds.sel(isobaricInhPa=[1000,925,850,700])
    ds.to_netcdf(target + f"E5pl00_1M_{year}_130_lt.nc")

1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
CPU times: user 56.7 s, sys: 57.3 s, total: 1min 54s
Wall time: 2min 39s

In [8]:
%%time

directory = "/pool/data/ERA5/E5/pl/an/1M/133/"

for year in years :
    print(year)
    ds = xr.open_dataset(directory + f"E5pl00_1M_{year}_133.grb", engine="cfgrib", indexpath='')
    ds = ds.sel(isobaricInhPa=[1000,925,850,700])
    ds.to_netcdf(target + f"E5pl00_1M_{year}_130_lt.nc")

1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
CPU times: user 1min 25s, sys: 33.1 s, total: 1min 58s
Wall time: 2min 13s